// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A personal support AI agent that offers advice on career, personal growth, and college life.
 *
 * - offerPersonalSupport - A function that handles the personal support process.
 * - OfferPersonalSupportInput - The input type for the offerPersonalSupport function.
 * - OfferPersonalSupportOutput - The return type for the offerPersonalSupport function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const OfferPersonalSupportInputSchema = z.object({
  topic: z.string().describe('The topic for personal support (career, personal growth, college life).'),
  userBackground: z.string().describe('Background information about the user to personalize the advice.'),
});
export type OfferPersonalSupportInput = z.infer<typeof OfferPersonalSupportInputSchema>;

const OfferPersonalSupportOutputSchema = z.object({
  advice: z.string().describe('Supportive advice in a casual Tanglish tone, with motivating words and emojis.'),
});
export type OfferPersonalSupportOutput = z.infer<typeof OfferPersonalSupportOutputSchema>;

export async function offerPersonalSupport(input: OfferPersonalSupportInput): Promise<OfferPersonalSupportOutput> {
  return offerPersonalSupportFlow(input);
}

const prompt = ai.definePrompt({
  name: 'offerPersonalSupportPrompt',
  input: {schema: OfferPersonalSupportInputSchema},
  output: {schema: OfferPersonalSupportOutputSchema},
  prompt: `Dei Gugan, unaku oru friend help panna poraen. I'm MachaGPT, remember? 😎 I'll give you advice on {{{topic}}} based on your background.

User Background: {{{userBackground}}}

Here's the advice, macha:

`,
  config: {
    safetySettings: [
      {
        category: 'HARM_CATEGORY_HATE_SPEECH',
        threshold: 'BLOCK_ONLY_HIGH',
      },
      {
        category: 'HARM_CATEGORY_DANGEROUS_CONTENT',
        threshold: 'BLOCK_NONE',
      },
      {
        category: 'HARM_CATEGORY_HARASSMENT',
        threshold: 'BLOCK_MEDIUM_AND_ABOVE',
      },
      {
        category: 'HARM_CATEGORY_SEXUALLY_EXPLICIT',
        threshold: 'BLOCK_LOW_AND_ABOVE',
      },
    ],
  },
});

const offerPersonalSupportFlow = ai.defineFlow(
  {
    name: 'offerPersonalSupportFlow',
    inputSchema: OfferPersonalSupportInputSchema,
    outputSchema: OfferPersonalSupportOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
